apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: haddley/books
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-react-deployment
  labels:
    app: books
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-react
  template:
    metadata:
      labels:
        app: books-react
    spec:
      containers:
      - name: books-react
        image: haddley/books-react
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: books-react-service
spec:
  selector:
    app: books-react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-reverse-proxy-deployment
  labels:
    app: books-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-reverse-proxy
  template:
    metadata:
      labels:
        app: books-reverse-proxy
    spec:
      containers:
      - name: books-reverse-proxy
        image: haddley/books-reverse-proxy
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-reverse-proxy-service
spec:
  selector:
    app: books-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer